version: '3.2'

services:
  database:
    image: postgres:10
    # image: mariadb
    container_name: project_db
    volumes:
      - type: bind
        source: "./volumes/db"
        target: "/var/lib/postgresql/data"
        # target: "/var/lib/mysql/data"
    networks:
      webapp_net:
    # If MariaDB is used, comment the 2 following lines.
    # The standard used port by default will be 3306.
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      # MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      # MYSQL_DATABASE: ${DATABASE_NAME}
      # MYSQL_USER: ${DATABASE_USER}
      # MYSQL_PASSWORD: ${DATABASE_PASSWORD}

  php:
    container_name: project_php
    build:
      context: context/php
      args:
        XDBG_IDEKEY: ${XDBG_IDEKEY}
        XDBG_REMOTE_PORT: ${XDBG_REMOTE_PORT}
        TIMEZONE: ${TIMEZONE}
        HOST_WWW_UID: ${HOST_WWW_UID}
        HOST_WWW_GID: ${HOST_WWW_GID}
    volumes:
      - type: bind
        source: "${HOST_WEBAPP_PATH}"
        target: "/var/www/code"
    networks:
      webapp_net:

  nginx:
    container_name: project_nginx
    build:
      context: ./context/nginx
      args:
        WEBAPP_DOMAIN: ${WEBAPP_DOMAIN}
    ports:
      - 80:80
    links:
      - php
    volumes:
      - type: bind
        source: "./volumes/logs/nginx/"
        target: "/var/log/nginx"
      - type: bind
        source: "${HOST_WEBAPP_PATH}"
        target: "/var/www/code"
    networks:
      webapp_net:
        ipv4_address: ${NET_WEBAPP_IP}

  # Mail catcher
  # Exposed ports: web interface on port 8025 and SMTP on 1025
  mail:
    container_name: project_mail
    image: blueimp/mailhog
    networks:
      webapp_net:
        ipv4_address: ${NET_WEBAPP_MAIL_IP}

networks:
  webapp_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${NET_SUBNET}
